name: Minecraft-Change-Skin-API
version: '${project.version}'
description: 'API for plugins to change the skin of a player on minecraft.net'
author: Janmm14
website: 'https://bitbucket.org/Janmm14/minecraft-change-skin'

load: STARTUP
main: de.janmm14.minecraftchangeskin.bukkit.Main
