name: Minecraft-Change-Skin-API
version: '${project.version}'
description: 'API for plugins to change the skin of a player on minecraft.net'
author: Janmm14
website: ''

load: STARTUP
main: de.janmm14.minecraftchangeskin.bukkit.Main
